Dockerfile
The deploy step was previously stricter so that tagged
commits might fail even though a PR or the master branch
was green.
=> rst-lint: add call from docker

.travis.yml
see:
- https://github.com/ome/zeroc-ice-py-manylinux#using-manylinux-packages
- https://github.com/ome/zeroc-ice-py-manylinux/blob/master/test/Dockerfile.centos7#L7-L8
=> Revert to manylinux to speed up builds

src/omero/gateway/__init__.py, src/omero/plugins/tag.py, src/omero/rtypes.py, src/omero/util/populate_metadata.py, src/omero_model_LengthI.py
Originally opened as https://github.com/joshmoore/omero-py/pull/13
=> More py3 test fixes

src/omero/install/jvmcfg.py, src/omero/util/text.py, test/unit/test_jvmcfg.py, test/unit/test_util.py, tox.ini
More unit test fixes
Test `test/unit/*.py` (previously ignored in tox.ini)
Amongst other things this should fix some of the problems with displaying tabular CLI output
=> More unit tests

src/omero/plugins/sessions.py, src/omero/plugins/user.py
see: https://github.com/ome/omero-py/pull/43
=> Use sys.exc_info rather than __traceback__

LICENSE.txt, README.rst
Instructions for a development installation of OMERO.py.
Also adds badges and a LICENSE
=> Readme dev setup instructions

src/omero/cli.py, src/omero/install/config_parser.py, src/omero/install/jvmcfg.py, src/omero/plugins/admin.py, src/omero/plugins/db.py, src/omero/util/upgrade_check.py, src/path.py, test/unit/clitest/test_admin.py
As we approach having merge-ci green, it's important to at least have tests _running_ on Python 3. This branch is intended to get py3-ci to a state where integration tests are run (without making merge-ci go red).
cc: @ome/python
=> Py3 sychronization

src/omero/util/populate_metadata.py
I expect these changes should be sufficient to fix:
- the failing OmeroPy.test.integration.metadata.test_populate tests
- the failing OmeroPy.test.integration.tablestest.test_populate_metadata test
=> Update populate_metadata utility classes following the code futurization

src/omero/gateway/__init__.py
Fixes I needed to get webclient running on python 3.7 with Django 1.11 (with https://github.com/ome/omero-web/pull/29)
=> Py3 webclient

src/omero/plugins/script.py
Add bracket to print in script
This should fix test like https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/28/testReport/junit/OmeroPy.test.integration.clitest.test_script/TestScript/testDemo/
=> py3: script

src/omero/plugins/script.py
Fix 
* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/27/testReport/junit/OmeroPy.test.integration.clitest.test_script/TestScript/testDemo/
* remaining flake8 issues
=> Py3 script

src/omero/plugins/fs.py
Change the mode
This should fix tests like
* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.fstest.test_rename/TestRename/test_rename_annotation/
* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.fstest.test_rename/TestRename/test_prep_and_delete/
=> plugins: fs

src/omero/gateway/__init__.py
Fixes: https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.gatewaytest.test_search_objects/TestGetObject/testSearchObjects/
=> fix test_search.testSearchObjects

src/omero/plugins/download.py
Fixes https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.clitest.test_download/TestDownload/testOriginalFileStdout__/
=> Fix fix_clitest.test_download handle std.out

src/omero/clients.py
Should fix https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/217/testReport/OmeroPy.test.integration.scriptstest.test_ping/TestPing/testPingViaISCript/
=> clients: handle unicode args (py2)

src/omero/gateway/__init__.py, src/omero/gateway/scripts/dbhelpers.py
Fixes https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/27/testReport/OmeroPy.test.integration.gatewaytest.test_image/TestImage/testChannelWavelengthUnits/
=> Fix gatewaytest testChannelWavelengthUnits

src/omero/plugins/obj.py
Message no longer exists
Print the error instead
* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.clitest.test_obj/TestObj/test_get_unknown_and_empty_field/
* https://py3-ci.openmicroscopy.org/jenkins/job/OMERO-test-integration/29/testReport/OmeroPy.test.integration.clitest.test_obj/TestObj/test_list_get/
=> plugins: obj

src/omero/gateway/__init__.py
Fixes new test: https://github.com/ome/openmicroscopy/pull/6170
Not sure how / why /when this has started failing.
=> fix testDeleteObjectDirect()

CHANGELOG.md
Happy to adjust the format. Once approved, happy to spread further across https://github.com/ome/omero-python-superbuild.
=> add skeleton change log file

src/omero_ext/pyinotify.py
see: https://github.com/ome/omero-dropbox/issues/6
=> pyinotify: python 3 fixes

src/omero/gateway/__init__.py
Fixes bug reported on Row 14 of https://docs.google.com/spreadsheets/d/1ry6vS0dmsylFQDAiIZDrPC3kXNpnHSMtK-2yj5X8jaU/edit#gid=420881033
"Multi-select images, then try to upload an attachment..."
=> batch annotate file fix

setup.py
see: https://forum.image.sc/t/connecting-napari-to-current-omero-server-5-4-9/31734/7
=> setup.py: windows builds

test/unit/clitest/test_basics.py
Follow-up from https://github.com/ome/omero-py/pull/140#issuecomment-561652861
=> Reenable testLoadGlob

setup.py
Original pinning stems from 2016.
=> Unpin pytest<3

README.rst
=> add conda snippet

src/omero/plugins/import.py
see: https://forum.image.sc/t/omero-5-6-upgrade-yaml-import-does-not-work/33787
=> Improve PyYAML error message

src/omero/plugins/sessions.py
Adds a `--show-uuid` option to sessions who
=> Add show-uuid option to sessions who

.travis.yml, tox.ini
Same as https://github.com/ome/omero-web/pull/152/
See for example error on https://github.com/ome/omero-py/pull/195#issuecomment-600190406
=> Remove pytest-sugar (incompatible pytest change)

.travis.yml
=> Attempt to fix Travis builds

CHANGELOG.md
Based on https://github.com/ome/omero-py/milestone/4?closed=1
(A couple of trivial PRs not mentioned).
=> Update changelog for 5.7.0

README.rst
/cc @jburel @joshmoore @manics
=> Update release paragraph to mention downstream conda repository

src/omero/cli.py
=> UTF-8 Fixes

CHANGELOG.md, setup.py
Includes unmerged PR:
Pending PRs:
=> Changelog notes for 5.8.0

src/omero/cli.py
=> Fix syntax issue in CLI argument parsing.

CHANGELOG.md
Note: still need to handle CLAs.
=> 5.9.3 changelog

src/omero/plugins/basics.py, src/omero/plugins/import.py, src/omero/util/cleanse.py
Point to image.sc
cc @dominikl
=> point to image.sc

CHANGELOG.md, README.rst, src/omero/gateway/__init__.py
changelog 5.11.1, and copyright update to 2022
=> Changelog 5.11.1

src/omero/plugins/_metadata_deprecated.py, src/omero/plugins/_upload_deprecated.py, src/omero/plugins/admin.py, src/omero/plugins/basics.py, src/omero/plugins/delete.py, src/omero/plugins/download.py, src/omero/plugins/export.py, src/omero/plugins/group.py, src/omero/plugins/hql.py, src/omero/plugins/ldap.py, src/omero/plugins/node.py, src/omero/plugins/perf.py, src/omero/plugins/prefs.py, src/omero/plugins/script.py, src/omero/plugins/submit.py, src/omero/plugins/tag.py, src/omero/plugins/user.py
Fix header in ``plugins`` package
=> fix header for doc generation

docs/conf.py
=> add source file

src/omero/util/temp_files.py
Noticed while working on doc generation
=> self.lock is always none

README.rst, src/omero/util/temp_files.py
Workaround discussed so we can generate the API doc.
Env variable set in readthedocs
=> add env variable to fix doc generation

CHANGELOG.md, README.rst, setup.py
=> changelog for 5.13.0

README.rst
=> use ome channel. conda-forge installs ice 3.7 binding

.github/workflows/workflow.yml
Upgrade checkout action to v3 and setup-python to v4 to avoid warnings
=> Upgrade action

setup.py
Bump ice version to 3.6.5 see https://github.com/ome/omero-py/issues/360
=> use ice 3.6.5

.readthedocs.yml
=> add missing config file

CHANGELOG.md
In preparation of the patch release
=> Add changelog for 5.19.6 release

src/omero/util/__init__.py, src/omero_ext/pyinotify.py
Update isSet to is_set to prevent warnings
=> switches stop_event.isSet for .is_set, fixes #476
